DAOS-216 build: Fix the "NoneType no require" issue
This patch fixes the following issue during traditional builds:

  $ scons
  scons: Reading SConscript files ...
  Using traditional build
  Checking for C library uuid... yes
  Checking for C library cmocka... yes
  Checking for C library crypto... yes
  Checking for C header file openssl/md5.h... yes
  Checking for C header file libpmemobj.h... yes
  AttributeError: 'NoneType' object has no attribute 'require':
    File "/home/liwei/daos_m/SConstruct", line 78:
      SConscript('build/src/SConscript', exports=['env', 'PREREQS'])
    File "/usr/lib/scons/SCons/Script/SConscript.py", line 604:
      return method(*args, **kw)
    File "/usr/lib/scons/SCons/Script/SConscript.py", line 541:
      return _SConscript(self.fs, *files, **subst_kw)
    File "/usr/lib/scons/SCons/Script/SConscript.py", line 250:
      exec _file_ in call_stack[-1].globals
    File "/home/liwei/daos_m/src/SConscript", line 20:
      PREREQS.require(env, 'hwloc')

Change-Id: Id58bbab58e96c6ae8cf797cbfff38770d1009e02
Signed-off-by: Li Wei <wei.g.li@intel.com>
Reviewed-on: https://review.whamcloud.com/24519
Tested-by: Jenkins
Reviewed-by: Liang Zhen <liang.zhen@intel.com>