CART-702 test: fix format overflow warning (#168)
Provide ample buffer space so that *printf() functions don't cause
errors like this:

= = = =
error: '%d' directive writing between 1 and 11 bytes into a region of
size between 0 and 254 [-Werror=format-overflow=]
= = = =

Signed-off-by: Yulu Jia <yulu.jia@intel.com>