(WIP) Enable VMD by default in Control Plane
TODO: Automate PCI_WHITELIST for DPDK params in all spdk init calls
Issues with daos_admin and io_server processes interferring with each other?

""
daos_io_server:0 EAL: Cannot open /dev/vfio/36: Device or resource busy
EAL: Failed to open group 36
EAL: Requested device 0000:5d:05.5 cannot be used
ERROR: daos_io_server:0 bdev_nvme.c:1861:bdev_nvme_library_init: *ERROR*: NVMe SSD "5d0505:01:00.0" could not be found.
bdev_nvme.c:1862:bdev_nvme_library_init: *ERROR*: Check PCIe BDF and that it is attached to UIO/VFIO driver.
bdev_nvme.c:1861:bdev_nvme_library_init: *ERROR*: NVMe SSD "5d0505:03:00.0" could not be found.
bdev_nvme.c:1862:bdev_nvme_library_init: *ERROR*: Check PCIe BDF and that it is attached to UIO/VFIO driver.
daos_io_server:0 EAL: Cannot open /dev/vfio/36: Device or resource busy
EAL: Failed to open group 36
EAL: Requested device 0000:5d:05.5 cannot be used
instance 0 exited: instance 0 exited prematurely: /home/smvanda/DAOS/install/bin/daos_io_server (instance 0) exited: exit status 1
ERROR: removing socket file: removing instance 0 socket file: no dRPC client set (data plane not started?)
""

If VMD devices are detected on the server and disable_vmd is NOT
set in the server config, the all VMD devices will be unbound using
the SPDK setup script and used.
A system can be determined to have VMD enabled if the following command
has any results: $lspci | grep "201d" or "Volume Management Device"
Seems that some systems use the device id (201d) and others use
"Volume Management Device" and 201d is not found.

Updates to daos_server.yml config:
- "disable_vmd" will disable automatic use of VMD
   disable_vmd: true
- "bdev_class" will be set to nvme, no additional bdev class for vmd
   bdev_class: nvme
- "enable_vmd" flag needs to be set
   enable_vmd: true
- "bdev_list" can now include regular NVMe SSDs and/or VMD Addrs
   bdev_list: ["0000:81:00.0","0000:5d:05.5"]

The VMD address in the bdev_list will NOT be used in the daos_nvme.conf
that is generated. Instead the backing transport IDs of the NVMe SSDs behind
the VMD addresses will be used.

Example of the DAOS NVMe configuration file with VMD enabled.
daos_nvme.conf:
	[VMD]
	  Enable True

	[Nvme]
          TransportID "trtype:PCIe traddr:5d0505:01:00.0" Nvme_boro-82.boro.hpdd.intel.com_0
          TransportID "trtype:PCIe traddr:5d0505:03:00.0" Nvme_boro-82.boro.hpdd.intel.com_1
          TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme_boro-82.boro.hpdd.intel.com_2
          RetryCount 4
          TimeoutUsec 0
          ActionOnTimeout None
          AdminPollRate 100000
          HotplugEnable No
          HotplugPollRate 0

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>