DAOS-6584 tests: Add missing self argument to
Add missing self argument to cleanup_processes to address this error:
  NameError: global name 'self' is not defined

Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>