DAOS-3935 control: Fix TestRunnerNormalExit failures
TestRunnerNormalExit sometimes fails like this:

  === RUN   TestRunnerNormalExit
  [...]
  DEBUG 03:44:10.845069 exec.go:113: daos_io_server:0 env:
  [D_LOG_MASK=DEBUG,MGMT=DEBUG,RPC=ERR,MEM=ERR OFI_INTERFACE=qib0]
  TestRunnerNormalExit INFO 2019/12/26 03:44:10 daos_io_server:0
  IOSERVER_TEST_ENV===D_LOG_MASK=DEBUG,MGMT=DEBUG,RPC=ERR,MEM=ERR
  OFI_INTERFACE=qib0
  [...]
  --- FAIL: TestRunnerNormalExit (1.13s)
      exec_test.go:187: wanted
      "OFI_INTERFACE=qib0 D_LOG_MASK=DEBUG,MGMT=DEBUG,RPC=ERR,MEM=ERR";
      got
      "D_LOG_MASK=DEBUG,MGMT=DEBUG,RPC=ERR,MEM=ERR OFI_INTERFACE=qib0"

Since os.Environ's doc does not say anything about the []string's order,
the test should sort the []string and its expectation itself.

Signed-off-by: Li Wei <wei.g.li@intel.com>