DAOS-5566 tests: remove main(), fix indentation
Wrong indentation in python breaks rpmbuild.  End of build.log file shows:
  ...
  Compiling /builddir/build/BUILDROOT/daos-1.1.3-1.5865.g21374b93.el7.x86_64/usr/lib/daos/TESTING/ftest/cart/cart_rpc_two_node.py ...
  Sorry: IndentationError: unexpected indent (cart_rpc_two_node.py, line 31)
  RPM build errors:
  error: Bad exit status from /var/tmp/rpm-tmp.5D8w8t (%install)
      Bad exit status from /var/tmp/rpm-tmp.5D8w8t (%install)
  Child return code was: 1
  EXCEPTION: [Error()]
  Traceback (most recent call last):
    File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
      result = func(*args, **kw)
    File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 789, in do_with_status
      raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
  mockbuild.exception.Error: Command failed:
   # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/daos.spec

Fix this Python/pylint error:
  NameError: name 'main' is not defined

We don't need to use the __main__ python idiom here, since we always invoke our
cart test python scripts via avocado.  In other words, they're always imported,
and not called directly.

Skip-build-leap15-rpm: true
Skip-func-test-leap15: true
Skip-build-ubuntu-clang: true
Skip-build-leap15-icc: true
Skip-coverity-test: true
Quick-build: true
Test-tag: cart
Skip-unit-tests: true
Skip-nlt: true
Skip-unit-test: true
Skip-unit-test-memcheck: true
Skip-coverity-test: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>