DAOS-3783 rdb: Fix rdb_raft_load_snapshot errors
The following assertion failures are observed during REBUILD tests:

  ERROR: daos_io_server:0 11/20-21:45:29.46 boro-38 DAOS[60694/60701]
    rdb EMRG src/rdb/rdb_raft.c:350 rdb_raft_load_snapshot() -1005
  daos_io_server: src/rdb/rdb_raft.c:350: rdb_raft_load_snapshot:
    Assertion `rc == 0' failed.

The errors behind these happened after servers received RDB snapshots.
Some expected RDB-internal akeys, like rdb_lc_nreplicas, were not found.

Wang Di found that this issue is due to recent VOS punch model changes.
This patch changes rdb_raft_exec_unpack_io to pass the snapshot base as
the epoch argument to vos_obj_update, based on discussions with Wang Di
and Jeff Oliver.

Signed-off-by: Li Wei <wei.g.li@intel.com>