CART-906 tests: Merge w/ master, fix gcc errors
  * Merge with master branch
  * Resolve conflicts (in rpc_one_node yaml file)
  * Resolve GCC errors
      error: dereferencing pointer to incomplete type
    Watch out for all the Boost macros, C Pre-processor
    calls, etc.

Skip-build-leap15-rpm: true
Skip-build-ubuntu-clang: true
Skip-build-leap15-icc: true
Skip-coverity-test: true
Skip-checkpatch: true
Quick-build: true
Test-tag: cart
Skip-func-test-leap15: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>