DAOS-13198 control: Improve error for insecure incompatibility
When running without certificates, the interoperability checks
cannot verify the peer component, and therefore inter-version
compatibility cannot be determined. The current error message
is a little confusing, so this commit adds a new fault with
a clearer description of the problem and proposed solution.

e.g.
$ dmg storage format
ERROR: dmg: server: code = 617 description = "versions 2.3.106 and 1.2.3 are not compatible in insecure mode"
ERROR: dmg: server: code = 617 resolution = "enable certificates or use identical component versions"

Required-githooks: true

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>