CORCI-812 release: Support releases from branches (#1717)
Also handle pre-releases which are any release with a - in it.
- I.e. 1.2.3-alpha1, 1.2.3-beta1, 1.2.3-rc1, etc.

Allow setting additional variables such as project and remote names.
- mostly for testing.

Fix CORCI-832 AttributeError: 'module' object has no attribute 'AlreadyExistsError'

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>