DAOS-5547 tests: Fix python syntax error
Caused a syntax error trying to eliminate pylint messages:
  hosts_with_multiple_entries =
  ...
  SyntaxError: invalid syntax

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>