Revert "CART-89 include: minor improvements to include/crt_types.h"
The change in crt_type.h cause build failure on boro node:
g++ -o build/Linux/src/utest/test_linkage.o -c -std=c++0x -g -Wall
-Werror -fpic -D_GNU_SOURCE -O2 -Isrc/include -Iinstall/Linux/include
-I/usr/include -Iinstall/Linux/include/na -Ibuild/Linux/src/include
-Isrc/include src/utest/test_linkage.cpp
src/utest/test_linkage.cpp:68: error: expected primary-expression before
'.' toke
g++ --version:
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

This reverts commit ab99b7e6b6ca93fd78cfd95db1957d9e6a6405a8.

Change-Id: I1a52e8d65e8f2c5bc617a66888697e514ebeb6e4
Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>
Reviewed-on: https://review.whamcloud.com/24082
Reviewed-by: Byron Marohn <byron.marohn@intel.com>
Reviewed-by: Liang Zhen <liang.zhen@intel.com>
Tested-by: Liang Zhen <liang.zhen@intel.com>
Tested-by: Maloo <hpdd-maloo@intel.com>