DAOS-16355 client: pydaos.torch cleanup improvements (#16630)
Initial implementation was relying on the Python garbage collector to
release the resources and close the connection, which led to
exceptions such as:

Exception ignored in: <function DaosClient.__del__ at 0x7fdf24a504c0>
Traceback (most recent call last):
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/__init__.py", line 63, in __del__
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/__init__.py", line 55, in _close
TypeError: 'NoneType' object is not callable

Exception ignored in: <function Checkpoint.__del__ at 0x7fdce3851e10>
Traceback (most recent call last):
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 568, in __del__
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 543, in close
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 648, in disconnect
AttributeError: 'NoneType' object has no attribute 'torch_disconnect'
Exception ignored in: <function Dataset.__del__ at 0x7fdce3851090>
Traceback (most recent call last):
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 162, in __del__
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 136, in close
  File "/home/denis/dev/enakta/pytorch/venv/lib/python3.10/site-packages/pydaos/torch/torch_api.py", line 648, in disconnect
AttributeError: 'NoneType' object has no attribute 'torch_disconnect'

Now, close() method and Python context manager protocol are
implemented, providing both manual and automatic resource management via
the `with` statement.

In addition, `DaosClient` singleton cleanup changed to happen when the module is
unloading, rather than during reaping by the garbage collector.

Signed-off-by: Denis Barakhtanov <dbarahtanov@enakta.com>