Resolving an python exception during core file processing.
Avoiding the "AttributeError: 'NoneType' object has no attribute 'find'"
error.

Also skipping the daos_core_test-rebuld.py tests as they cause out of
disk space issue that prevent the validation of the changes for the
original problem.

Test-tag-hw-medium: pr,hw,medium,ib2,-daos_test_rebuild

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>