Install binaries under /usr/local to address build failure since /usr has the libfabric version installed by the distribution. This is causing this:
libna.so.2: undefined reference to `fi_dupinfo@FABRIC_1.3'
libna.so.2: undefined reference to `fi_freeinfo@FABRIC_1.3'
libna.so.2: undefined reference to `fi_getinfo@FABRIC_1.3'

Skip-test: true
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>