DAOS-19648 build: Fail on unknown SCons variables
There are default build variables in SConstruct such as TARGET_TYPE
and PREFIX. User can override them, but if there's a typo, SConstruct
silently ignores it and user would think that their override was
successful.

To avoid this false negative, add opts.UnknownVariables() to check
whether unknown variables are passed in (most likely due to typo).

Tested the following and it printed appropriate error message.

scons-3 --check-only --config=force install -j 8 --implicit-deps-changed BUILD_TYPE=debug TARGET_TPYE=debug
scons-3 --check-only --config=force install -j 8 --implicit-deps-changed PERFIX=/opt/daos

Error message:
ERROR: Unknown scons variable(s): TARGET_TPYE
ERROR: Unknown scons variable(s): PERFIX

skip-unit-tests: true
skip-test: true
Signed-off-by: Makito Kano <makito.kano@hpe.com>