Revert "CORDAOSM-1 dtp: change daos_transport.h for C++ compatible"
This reverts commit 381eea2de3409f3854208131f98ab15b4fa4aa4b.

This causes compile problems from C++ code:

src/include/daos/daos_transport.h:699:12: error: invalid use of 'static' in linkage specification
 extern "C" static  inline int      \
            ^
src/include/daos/daos_transport.h:732:2: note: in expansion of macro '_DTP_GEN_STRUCT_PROC'
  _DTP_GEN_STRUCT_PROC(struct_type_name, fields)
  ^

Change-Id: I7e0c0185bb91ab9f3a71f853ab2d9b52227012b8
Reviewed-on: http://review.whamcloud.com/18967
Reviewed-by: Johann Lombardi <johann.lombardi@intel.com>
Tested-by: Johann Lombardi <johann.lombardi@intel.com>