DAOS-1449 client daos_obj_fetch iod null causes segfault
Got segfault at IO13 with NULL injected to daos_obj_fatch:
reading un-existed record ...
[ ERROR ] — Test failed with exception: Segmentation fault(11)

With the fix, got an error without segfault:
reading un-existed record ...
[  ERROR   ] --- 0xfffffffffffffc15 != 0
[   LINE   ] --- src/tests/suite/daos_obj.c:1943: error: Failure!

Change-Id: I48127f96d3fad953376e6d4ef78aa4742295529e
Signed-off-by: Hua Kuang <hua.kuang@intel.com>